from itertools import combinations
from types import SimpleNamespace

import numpy as np
import pandas as pd

from .fit import (
    _attach_formula_if_reconstructible,
    _build_selection_groups,
    _fit_matrices,
)
from .parse_formula import parse_formula


def bsr(
    formula,
    data,
    max_var=8,
    metric="aic",
    method="ols",
    group_categorical=False,
    **kwargs,
):
    """
    Perform Best Subset Regression using OLS, Logistic, Poisson, or GLM.

    Parameters
    ----------
    formula : str
        Regression formula (e.g., ``'Y ~ X1 + X2'``).
    data : pandas.DataFrame
        Dataset containing the variables.
    max_var : int, default=8
        Maximum number of selection terms to consider. With
        ``group_categorical=True``, an entire categorical predictor counts as
        one term even when it produces multiple dummy columns.
    metric : {'adjr2', 'aic', 'bic', 'rmse'}, default='aic'
        Model-selection metric.
    method : {'ols', 'logistic', 'poisson', 'glm'}, default='ols'
        Fitting method.
    group_categorical : bool, default=False
        If False, preserve Ravix's historical behavior and allow individual
        dummy columns from a multilevel categorical predictor to be selected
        separately. If True, all dummy columns generated by each categorical
        main-effect predictor are selected together as one term.
    **kwargs
        Additional arguments passed to the fitting function.

    Returns
    -------
    statsmodels model
        Best fitted model with selection results available through ``model.bsr``.
    """
    categorical_levels = {}
    Y, X = parse_formula(
        formula,
        data,
        categorical_levels=categorical_levels,
    )

    actual_predictors = [
        col for col in X.columns if col not in ["Intercept", "const"]
    ]
    selection_groups = _build_selection_groups(
        actual_predictors,
        categorical_levels,
        group_categorical=group_categorical,
    )
    selectable_terms = list(selection_groups)

    metric_column = {
        "adjr2": "Adj. R-squared",
        "aic": "AIC",
        "bic": "BIC",
        "rmse": "RMSE",
    }
    if metric not in metric_column:
        raise ValueError("Invalid metric. Choose from: 'adjr2', 'aic', 'bic', 'rmse'.")
    if method in ["logistic", "poisson", "glm"] and metric == "rmse":
        raise ValueError(f"RMSE is not valid for {method} regression.")
    if not selectable_terms:
        raise ValueError("No predictor variables found after parsing formula.")

    max_var = min(max_var, len(selectable_terms))
    if max_var <= 0:
        raise ValueError("max_var must be positive and there must be predictor variables.")

    def get_subsets(variables, max_size):
        return [
            subset
            for k in range(1, max_size + 1)
            for subset in combinations(variables, k)
        ]

    def expand_terms(terms):
        columns = []
        for term in terms:
            columns.extend(selection_groups[term])
        return columns

    def subset_matrix(terms):
        columns = expand_terms(terms)
        X_subset = X[columns].copy()
        if "Intercept" in X.columns:
            X_subset = pd.concat([X[["Intercept"]].copy(), X_subset], axis=1)
        elif "const" in X.columns:
            X_subset = pd.concat([X[["const"]].copy(), X_subset], axis=1)
        return X_subset

    def get_metrics(model):
        n = model.nobs
        p = model.df_model + 1
        if method == "ols":
            mse = np.sum(model.resid**2) / (n - p)
            rmse = np.sqrt(mse)
        else:
            rmse = np.nan
        return (
            model.rsquared_adj if hasattr(model, "rsquared_adj") else np.nan,
            model.aic,
            model.bic,
            rmse,
        )

    results = []
    failed_subsets = []

    for subset in get_subsets(selectable_terms, max_var):
        try:
            model = _fit_matrices(
                Y,
                subset_matrix(subset),
                method=method,
                **kwargs,
            )
            adjr2, aic, bic, rmse = get_metrics(model)
            results.append((subset, adjr2, aic, bic, rmse))
        except Exception as exc:
            failed_subsets.append((subset, str(exc)))

    if not results:
        raise RuntimeError(
            f"No models could be fitted successfully. Failed subsets: {failed_subsets}"
        )

    results_df = pd.DataFrame(
        results,
        columns=["Features", "Adj. R-squared", "AIC", "BIC", "RMSE"],
    )

    metric_col = metric_column[metric]
    if results_df[metric_col].isna().all():
        raise ValueError(
            f"All models have NaN values for metric '{metric}'. "
            "Check your data and model specification."
        )

    results_df_clean = results_df.dropna(subset=[metric_col])
    if results_df_clean.empty:
        raise ValueError(
            f"No valid models found for metric '{metric}' after removing NaN values."
        )

    ascending = metric != "adjr2"
    results_df_clean = results_df_clean.sort_values(
        by=metric_col,
        ascending=ascending,
    )

    best_features = list(results_df_clean.iloc[0]["Features"])
    best_model = _fit_matrices(
        Y,
        subset_matrix(best_features),
        method=method,
        **kwargs,
    )

    response_term = formula.split("~", 1)[0].strip()
    _attach_formula_if_reconstructible(
        best_model,
        response_term,
        categorical_levels,
    )

    best_by_k = {}
    k_groups = results_df_clean.groupby(results_df_clean["Features"].apply(len))
    for k, group in k_groups:
        if ascending:
            best_row = group.loc[group[metric_col].idxmin()]
        else:
            best_row = group.loc[group[metric_col].idxmax()]
        best_by_k[k] = list(best_row["Features"])

    best_model.bsr = SimpleNamespace(
        best_features=best_features,
        best_by_k=best_by_k,
        results=results_df_clean,
        metric=metric,
        method=method,
        group_categorical=group_categorical,
        groups=selection_groups,
        all_features=selectable_terms,
        n_subsets_tested=len(results),
        failed_subsets=failed_subsets if failed_subsets else None,
    )

    return best_model
