from types import SimpleNamespace

import pandas as pd

from .fit import (
    _attach_formula_if_reconstructible,
    _build_selection_groups,
    _fit_matrices,
)
from .parse_formula import parse_formula


def stepwise(
    formula,
    data,
    method="ols",
    direction="backward",
    metric="aic",
    threshold_in=0.05,
    threshold_out=0.10,
    max_steps=100,
    verbose=False,
    group_categorical=False,
    **kwargs,
):
    """
    Perform stepwise model selection based on a specified metric.

    Parameters
    ----------
    formula : str
        A regression formula of the form 'Y ~ X1 + X2 + ...'.
    data : pandas.DataFrame
        The dataset containing the variables in the formula.
    method : str, default='ols'
        Model type: 'ols', 'logistic', 'poisson', 'glm'.
    direction : {'forward', 'backward', 'both'}, default='backward'
        Direction of selection.
    metric : {'aic', 'bic', 'adjr2', 'pvalue'}, default='aic'
        Metric used to evaluate model performance at each step.
    threshold_in : float, default=0.05
        Currently unused; retained for backward compatibility.
    threshold_out : float, default=0.10
        Currently unused; retained for backward compatibility.
    max_steps : int, default=100
        Maximum number of steps before stopping.
    verbose : bool, default=False
        If True, print progress messages.
    group_categorical : bool, default=False
        If False, preserve Ravix's historical behavior and allow individual
        dummy columns from a multilevel categorical predictor to enter or leave
        separately. If True, all dummy columns generated by each categorical
        main-effect predictor enter or leave together as one selection term.
    **kwargs
        Additional arguments passed to the fitting function.

    Returns
    -------
    model : statsmodels object
        Final selected model. Selection details are available through
        ``model.step``, including ``model.step.failed_candidates``: a list of
        candidates that could not be fit or scored during the search (each a
        dict with ``step``, ``action``, ``variable``, and ``reason``). This is
        populated regardless of ``verbose``.

    Raises
    ------
    ValueError
        If ``direction`` is ``'forward'`` or ``'both'`` and the formula
        excludes the intercept (e.g. via ``-1`` or ``+0``): those directions
        start from the empty model, and a model with no predictors and no
        intercept has nothing to fit. Use ``direction='backward'`` (which
        starts from the full model), or include an intercept in the formula.
    RuntimeError
        If every candidate actually attempted at a forward-selection or
        backward-elimination step fails to fit. This is distinct from the
        ordinary "no candidate improved the score" stopping condition: it
        means every fit attempted at that step raised an error, which more
        often indicates a genuine data or configuration problem than a
        natural end to the search. The raised exception carries a
        ``failed_candidates`` attribute (same structure as
        ``model.step.failed_candidates``) covering every failure recorded up
        to and including the one that triggered it, since the search did not
        complete and there is no returned model to attach it to.
    """

    if direction not in {"forward", "backward", "both"}:
        raise ValueError("Invalid direction. Choose from: 'forward', 'backward', 'both'.")
    if metric not in {"aic", "bic", "adjr2", "pvalue"}:
        raise ValueError("Invalid metric. Choose from: 'aic', 'bic', 'adjr2', 'pvalue'.")

    def get_score(model):
        if metric == "aic":
            return model.aic
        if metric == "bic":
            return model.bic
        if metric == "adjr2":
            return 1 - (1 - model.rsquared) * (model.nobs - 1) / (
                model.nobs - model.df_model - 1
            )

        intercept_names = ["Intercept", "const", "Const"]
        pvals_no_intercept = model.pvalues.copy()
        for intercept_name in intercept_names:
            pvals_no_intercept = pvals_no_intercept.drop(intercept_name, errors="ignore")
        return pvals_no_intercept.max() if len(pvals_no_intercept) > 0 else 0

    categorical_levels = {}
    Y_out, X_out = parse_formula(
        formula,
        data,
        categorical_levels=categorical_levels,
    )

    actual_predictors = [
        col for col in X_out.columns if col not in ["Intercept", "const"]
    ]
    has_intercept = any(col in X_out.columns for col in ["Intercept", "const"])
    intercept_col = (
        "Intercept"
        if "Intercept" in X_out.columns
        else ("const" if "const" in X_out.columns else None)
    )

    selection_groups = _build_selection_groups(
        actual_predictors,
        categorical_levels,
        group_categorical=group_categorical,
    )
    selectable_terms = list(selection_groups)

    label = metric.upper()

    # Selected/remaining contain selection-term names, not design-matrix columns.
    # With group_categorical=False these are identical to the historical column
    # names. With grouping enabled a categorical term expands to all its dummies.
    if direction in ["forward", "both"]:
        selected = []
        remaining = selectable_terms.copy()
    else:
        selected = selectable_terms.copy()
        remaining = []

    def expand_terms(terms):
        columns = []
        for term in terms:
            columns.extend(selection_groups[term])
        return columns

    def has_fittable_terms(terms):
        """A candidate needs at least one predictor column or an intercept.

        Without either, there is nothing to fit: passing an empty design
        matrix straight to statsmodels raises an opaque, unrelated numpy
        error ("zero-size array to reduction operation maximum which has no
        identity") rather than anything that names the actual problem. This
        lets every call site recognize that case up front instead of relying
        on the fit failing and being caught.
        """
        return bool(expand_terms(terms)) or (has_intercept and intercept_col is not None)

    def model_from_terms(terms):
        predictor_vars = expand_terms(terms)
        if predictor_vars:
            X_subset = X_out[predictor_vars].copy()
            if has_intercept and intercept_col:
                X_subset = pd.concat(
                    [X_out[[intercept_col]].copy(), X_subset], axis=1
                )
        elif has_intercept and intercept_col:
            X_subset = X_out[[intercept_col]].copy()
        else:
            # Callers are expected to check has_fittable_terms() first, so this
            # should be unreachable; kept as a clear error rather than letting
            # an empty X_out reach _fit_matrices if some caller doesn't.
            raise ValueError(
                "Cannot fit a model with no predictors and no intercept "
                f"(formula '{formula}' excludes the intercept)."
            )

        return _fit_matrices(Y_out, X_subset, method=method, **kwargs)

    if not has_fittable_terms(selected):
        raise ValueError(
            f"stepwise() cannot start {direction} selection from an empty model: "
            f"the formula '{formula}' excludes the intercept (e.g. via '-1' or "
            "'+0'), so there is nothing to fit until at least one predictor is "
            "selected. Use direction='backward' (which starts from the full "
            "model), or include an intercept in the formula."
        )

    best_model = model_from_terms(selected)
    current_score = get_score(best_model)

    step_history = [
        {
            "step": 0,
            "action": "initial",
            "variable": None,
            "score": current_score,
            "variables": selected.copy(),
        }
    ]
    initial_variables = selected.copy()
    failed_candidates = []

    if verbose:
        print(f"Initial {label} = {current_score:.4f}")

    step_count = 0
    while step_count < max_steps:
        step_count += 1
        changed = False

        if direction in ["forward", "both"]:
            scores = []
            attempted = 0
            for term in remaining:
                # Adding a term to any existing set can never produce an empty,
                # unfittable candidate, so no has_fittable_terms() check is
                # needed here -- every candidate here is a genuine fit attempt.
                trial_terms = selected + [term]
                attempted += 1
                try:
                    model = model_from_terms(trial_terms)
                    scores.append((get_score(model), term, model))
                except Exception as exc:
                    failed_candidates.append(
                        {
                            "step": step_count,
                            "action": "add",
                            "variable": term,
                            "reason": str(exc),
                        }
                    )
                    if verbose:
                        print(f"Failed to fit model with {term}: {exc}")

            if attempted and not scores:
                # Every candidate we actually tried to fit this step raised an
                # error -- not "nothing improved," but "nothing could even be
                # scored." Silently falling through to "no improvement found"
                # would hide a real problem, so this is raised instead of
                # returned. failed_candidates is attached to the exception
                # itself because the function never reaches its return here,
                # so there is no model to hang model.step off of.
                error = RuntimeError(
                    f"All {attempted} candidate model(s) failed to fit during "
                    f"forward selection at step {step_count}; none could be "
                    "scored. See the .failed_candidates attribute on this "
                    "exception for the individual errors."
                )
                error.failed_candidates = list(failed_candidates)
                raise error

            if scores:
                best = (
                    min(scores, key=lambda x: x[0])
                    if metric in ["aic", "bic", "pvalue"]
                    else max(scores, key=lambda x: x[0])
                )
                improved = (
                    best[0] < current_score
                    if metric in ["aic", "bic", "pvalue"]
                    else best[0] > current_score
                )
                if improved:
                    selected.append(best[1])
                    remaining.remove(best[1])
                    best_model = best[2]
                    current_score = best[0]
                    changed = True
                    step_history.append(
                        {
                            "step": step_count,
                            "action": "add",
                            "variable": best[1],
                            "score": current_score,
                            "variables": selected.copy(),
                        }
                    )
                    if verbose:
                        print(
                            f"Step {step_count}: add {best[1]} "
                            f"({label}={current_score:.4f})"
                        )

        if direction in ["backward", "both"] and selected:
            scores = []
            attempted = 0
            for term in selected:
                trial_terms = [candidate for candidate in selected if candidate != term]

                if not has_fittable_terms(trial_terms):
                    # Removing this term would leave no predictors and no
                    # intercept -- nothing would be left to fit, so this
                    # candidate can never be a valid choice. Skip it
                    # explicitly with a clear reason instead of calling the
                    # fit and relying on the resulting numpy error being
                    # caught below. This is an expected, valid skip, not a
                    # fit attempt, so it does not count toward `attempted`.
                    failed_candidates.append(
                        {
                            "step": step_count,
                            "action": "remove",
                            "variable": term,
                            "reason": (
                                "would remove the last remaining term from a "
                                "model with no intercept, leaving nothing to fit"
                            ),
                        }
                    )
                    if verbose:
                        print(
                            f"Skipping removal of {term}: would leave no "
                            "predictors and no intercept to fit."
                        )
                    continue

                attempted += 1
                try:
                    model = model_from_terms(trial_terms)
                    scores.append((get_score(model), term, model))
                except Exception as exc:
                    failed_candidates.append(
                        {
                            "step": step_count,
                            "action": "remove",
                            "variable": term,
                            "reason": str(exc),
                        }
                    )
                    if verbose:
                        print(f"Failed to fit model without {term}: {exc}")

            if attempted and not scores:
                # Same reasoning as the forward-selection guard above: every
                # candidate we actually attempted to fit this step failed, so
                # this is raised rather than silently treated as "no
                # improvement found."
                error = RuntimeError(
                    f"All {attempted} candidate model(s) failed to fit during "
                    f"backward elimination at step {step_count}; none could "
                    "be scored. See the .failed_candidates attribute on this "
                    "exception for the individual errors."
                )
                error.failed_candidates = list(failed_candidates)
                raise error

            if scores:
                best = (
                    min(scores, key=lambda x: x[0])
                    if metric in ["aic", "bic", "pvalue"]
                    else max(scores, key=lambda x: x[0])
                )
                improved = (
                    best[0] < current_score
                    if metric in ["aic", "bic", "pvalue"]
                    else best[0] > current_score
                )
                if improved:
                    selected.remove(best[1])
                    if best[1] not in remaining:
                        remaining.append(best[1])
                    best_model = best[2]
                    current_score = best[0]
                    changed = True
                    step_history.append(
                        {
                            "step": step_count,
                            "action": "remove",
                            "variable": best[1],
                            "score": current_score,
                            "variables": selected.copy(),
                        }
                    )
                    if verbose:
                        print(
                            f"Step {step_count}: remove {best[1]} "
                            f"({label}={current_score:.4f})"
                        )

        if not changed:
            if verbose:
                print(f"No improvement found. Stopping at step {step_count}.")
            break

    final_variables = selected.copy()

    response_term = formula.split("~", 1)[0].strip()
    _attach_formula_if_reconstructible(
        best_model,
        response_term,
        categorical_levels,
    )

    if verbose:
        print(f"Final {label} = {current_score:.4f}")

    best_model.step = SimpleNamespace(
        direction=direction,
        metric=metric,
        group_categorical=group_categorical,
        groups=selection_groups,
        history=step_history,
        initial_variables=initial_variables,
        final_variables=final_variables,
        initial_score=step_history[0]["score"],
        final_score=current_score,
        n_steps=len(step_history) - 1,
        failed_candidates=failed_candidates,
    )

    return best_model
